// =============================================
// Centralized Font Mock Data — Akshara Type Studio
// All typeface data used across fonts, featured, and detail pages
// =============================================

export type FontCategory = "Serif" | "Sans" | "Display" | "Calligraphy" | "Heritage" | "Variable";
export type FontStatus = "Available" | "Coming Soon" | "Custom Only";

export interface Font {
  id: number;
  name: string;
  nameKannada: string;
  char: string;
  desc: string;
  longDesc: string;
  styles: number | "Variable";
  category: FontCategory;
  status: FontStatus;
  year: string;
  tag?: string;
  weights: number[];
  features: string[];
  inspiration: string;
  usage: string[];
}

export const fontData: Font[] = [
  {
    id: 1,
    name: "Chikkamagaluru",
    nameKannada: "ಚಿಕ್ಕಮಗಳೂರು",
    char: "ಅ",
    desc: "A serif face with modern rhythm, optimized for literary display and digital long-form.",
    longDesc: "Chikkamagaluru draws its essence from the misty coffee plantations and colonial-era printing presses of Karnataka's hill districts. Its strokes echo the careful hand of early 20th-century Kannada book typesetters.",
    styles: 12,
    category: "Serif",
    status: "Available",
    year: "2023",
    tag: "NEW",
    weights: [100, 200, 300, 400, 500, 600, 700, 800, 900],
    features: ["Standard Ligatures", "Optical Kerning", "Oldstyle Figures", "Stylistic Alternates"],
    inspiration: "Chikkamagaluru coffee estate colonial typefaces",
    usage: ["Editorial", "Book Design", "Branding", "Web"],
  },
  {
    id: 2,
    name: "Bengaluru LED",
    nameKannada: "ಬೆಂಗಳೂರು LED",
    char: "ಬೆ",
    desc: "Digital-first dot matrix inspired by the garden city's tech-driven signage.",
    longDesc: "A homage to the LED hoardings of MG Road and Brigade Road, Bengaluru LED captures the kinetic energy of India's Silicon Valley through a geometric dot-matrix system faithfully adapted to the Kannada script.",
    styles: 4,
    category: "Display",
    status: "Available",
    year: "2023",
    tag: "POPULAR",
    weights: [400, 700],
    features: ["Discretionary Ligatures", "Tabular Figures"],
    inspiration: "Bengaluru LED billboards and tech hoardings",
    usage: ["Branding", "Poster", "Digital Signage"],
  },
  {
    id: 3,
    name: "Bengaluru Sans",
    nameKannada: "ಬೆಂಗಳೂರು ಸ್ಯಾನ್ಸ್",
    char: "ಅ",
    desc: "High-legibility sans-serif for the modern Kannadiga. Geometric and clear.",
    longDesc: "Built from first principles for screen readability. Bengaluru Sans is a neo-grotesque that harmonizes the circular nature of Kannada characters with the geometric discipline of contemporary UI typefaces.",
    styles: 9,
    category: "Sans",
    status: "Available",
    year: "2022",
    weights: [300, 400, 500, 600, 700, 800, 900],
    features: ["Standard Ligatures", "Optical Kerning", "Fractions", "Ordinals"],
    inspiration: "Swiss neo-grotesque adapted for Indic scripts",
    usage: ["UI / App", "Branding", "Signage", "Web"],
  },
  {
    id: 4,
    name: "Bandipura",
    nameKannada: "ಬಂಡೀಪುರ",
    char: "ಶ",
    desc: "Organic and fluid, inspired by the sanctuary's wilderness. A calligraphic masterpiece.",
    longDesc: "Written with a broad-nib pen held at the angle of a Karnataka forest trail, Bandipura Script flows like the Kabini river. Each letter form is drawn from motion studies of wildlife signage in India's oldest national park.",
    styles: 8,
    category: "Calligraphy",
    status: "Available",
    year: "2021",
    weights: [300, 400, 600, 700],
    features: ["Contextual Swashes", "Stylistic Alternates", "Historical Ligatures"],
    inspiration: "Karnataka forest trail signage and palm-leaf manuscripts",
    usage: ["Logos", "Packaging", "Heritage Branding"],
  },
  {
    id: 5,
    name: "Kadamba Display",
    nameKannada: "ಕಾದಂಬ ಡಿಸ್ಪ್ಲೇ",
    char: "ಕಾ",
    desc: "High-contrast display face inspired by 4th-century royal inscriptions.",
    longDesc: "The Kadamba dynasty gave Karnataka its first script. This typeface reconstructs the angular authority of Kadamba-era stone tablets into a razor-sharp display face for titles, posters, and brand marks requiring regal weight.",
    styles: 6,
    category: "Heritage",
    status: "Available",
    year: "2023",
    tag: "FEATURED",
    weights: [400, 500, 600, 700, 800, 900],
    features: ["Contextual Alternates", "Case-Sensitive Forms", "Historical Forms"],
    inspiration: "4th century Kadamba dynasty stone inscriptions, Banavasi",
    usage: ["Headline", "Poster", "Brand Identity"],
  },
  {
    id: 6,
    name: "Sahitya Serif",
    nameKannada: "ಸಾಹಿತ್ಯ ಸೆರಿಫ್",
    char: "ಸ",
    desc: "Crafted for high-end editorial and complex literary layouts. Timeless and regal.",
    longDesc: "Named for Karnataka's rich literary tradition — Sahitya Serif is a workhorse for long-form Kannada publishing. Its generous x-height and carefully spaced ascenders make multi-column newspaper layouts effortless.",
    styles: 14,
    category: "Serif",
    status: "Available",
    year: "2022",
    weights: [100, 200, 300, 400, 500, 600, 700, 800, 900],
    features: ["Standard Ligatures", "Small Caps", "Oldstyle Figures", "Optical Size"],
    inspiration: "Classical Devanagari serifs adapted for Kannada letterforms",
    usage: ["Books", "Newspapers", "Magazines", "Academic"],
  },
  {
    id: 7,
    name: "Mysuru Mono",
    nameKannada: "ಮೈಸೂರು ಮೊನೊ",
    char: "ಮ",
    desc: "The studio's first monospaced typeface, bringing technical precision to Kannada code.",
    longDesc: "The palace city meets the terminal window. Mysuru Mono is a fixed-pitch typeface designed for developers who write Kannada. Every character occupies exactly the same width, enabling pixel-perfect alignment in code editors.",
    styles: 3,
    category: "Sans",
    status: "Available",
    year: "2024",
    tag: "TECHNICAL",
    weights: [400, 700],
    features: ["Tabular Figures", "Slashed Zero", "Coding Ligatures"],
    inspiration: "JetBrains Mono and Iosevka design principles adapted for Kannada",
    usage: ["Code Editors", "Terminal", "Technical Documentation"],
  },
  {
    id: 8,
    name: "Hampi Stone",
    nameKannada: "ಹಂಪಿ ಸ್ಟೋನ್",
    char: "ಹ",
    desc: "Tactile and heavy, mimicking the granite carvings of the Vijayanagara empire.",
    longDesc: "Walking through Hampi's ruins, you see letters chiselled with an authority that no digital type can easily replicate. Hampi Stone is our attempt — a slab-serif with brutalist weight and incised letterforms drawn from site photography.",
    styles: 1,
    category: "Heritage",
    status: "Available",
    year: "2021",
    weights: [900],
    features: ["Historical Forms", "Case-Sensitive Forms"],
    inspiration: "15th-century Vijayanagara granite inscriptions, Hampi UNESCO site",
    usage: ["Titles", "Heritage Projects", "Museum Installations"],
  },
  {
    id: 9,
    name: "Vidhana Sans",
    nameKannada: "ವಿಧಾನ ಸ್ಯಾನ್ಸ್",
    char: "ವಿ",
    desc: "Authoritative and grand, designed for administrative and governmental clarity.",
    longDesc: "The Karnataka Vidhana Soudha is a monument to authority. Vidhana Sans takes its proportional cues from architectural neoclassicism, delivering a humanist sans that reads powerfully in large-format state communications and government publications.",
    styles: 7,
    category: "Sans",
    status: "Available",
    year: "2023",
    weights: [300, 400, 500, 600, 700, 800, 900],
    features: ["Standard Ligatures", "Fractions", "Small Caps", "Tabular Figures"],
    inspiration: "Humanist sans proportions with Vidhana Soudha architectural geometry",
    usage: ["Government", "Institutional", "Wayfinding", "Signs"],
  },
  {
    id: 10,
    name: "Kavi Script",
    nameKannada: "ಕವಿ ಲಿಪಿ",
    char: "ಕ",
    desc: "A flowing cursive inspired by 18th-century royal correspondence.",
    longDesc: "Discovered in the Mysuru Palace library, a collection of Woddeyar dynastic letters penned in an exquisite cursive hand formed the blueprint for Kavi Script. Each letterform is traced directly from archival photographs, then refined for digital precision.",
    styles: 2,
    category: "Calligraphy",
    status: "Available",
    year: "2022",
    weights: [400, 700],
    features: ["Contextual Swashes", "Historical Forms", "Stylistic Sets"],
    inspiration: "18th-century Mysuru Woddeyar palace correspondence manuscripts",
    usage: ["Invitations", "Luxury Packaging", "Certificates", "Heritage Branding"],
  },
  {
    id: 11,
    name: "Tunga Variable",
    nameKannada: "ತುಂಗ ವೇರಿಯೇಬಲ್",
    char: "ತು",
    desc: "Infinite weights in one file. The future of Kannada responsive typography.",
    longDesc: "Named for the Tunga river that mirrors the sky, Tunga Variable is a full-axis variable font with continuous control over Weight, Width, and Optical Size axes. One file replaces a complete family while enabling micro-typographic nuance impossible before variable technology.",
    styles: "Variable",
    category: "Variable",
    status: "Available",
    year: "2024",
    tag: "VARIABLE",
    weights: [100, 900],
    features: ["Variable Weight Axis", "Variable Width Axis", "Optical Size Axis", "All OpenType Features"],
    inspiration: "Variable font technology with Tunga river organic curves",
    usage: ["Responsive Web", "App UI", "All Contexts"],
  },
  {
    id: 12,
    name: "Karavali Display",
    nameKannada: "ಕರಾವಳಿ ಡಿಸ್ಪ್ಲೇ",
    char: "ಕ",
    desc: "Bold and fluid as the Arabian sea. Perfect for branding and posters.",
    longDesc: "Born from the Tulu coast, where the land and sea are in constant dialogue, Karavali Display captures the energy of coastal Karnataka. Its wave-like counters and dynamic stroke contrast make it ideal for bold brand expressions.",
    styles: 5,
    category: "Display",
    status: "Available",
    year: "2024",
    tag: "NEW",
    weights: [400, 500, 600, 700, 900],
    features: ["Contextual Alternates", "Stylistic Alternates", "Swashes"],
    inspiration: "Arabian sea waves meeting the Karnataka coastal rock formations",
    usage: ["Branding", "Posters", "Packaging", "Social Media"],
  },
  {
    id: 13,
    name: "Coorg Slab",
    nameKannada: "ಕೊಡಗು ಸ್ಲ್ಯಾಬ್",
    char: "ಕ",
    desc: "A robust slab-serif built for outdoor advertising in the hill districts.",
    longDesc: "Designed for durability and impact in the misty hills of Kodagu, Coorg Slab is a heavy slab-serif that reads at distance and at scale. Its squared serifs and sturdy strokes resist visual noise in complex environments.",
    styles: 5,
    category: "Serif",
    status: "Available",
    year: "2022",
    weights: [300, 400, 600, 700, 800],
    features: ["Standard Ligatures", "Tabular Figures", "Small Caps"],
    inspiration: "Outdoor advertising in Kodagu's coffee estate hoardings",
    usage: ["Outdoor Advertising", "Packaging", "Retail"],
  },
  {
    id: 14,
    name: "Pattadakal Caps",
    nameKannada: "ಪಟ್ಟದಕಲ್ ಕ್ಯಾಪ್ಸ್",
    char: "ಪ",
    desc: "All-caps heritage display inspired by UNESCO Chalukya temple inscriptions.",
    longDesc: "The Chalukya temples of Pattadakal bear some of the most sophisticated inscriptions in Indian heritage. Pattadakal Caps distils the architectural geometry of 8th-century Chalukya letterforms into a contemporary all-caps display face.",
    styles: 3,
    category: "Heritage",
    status: "Available",
    year: "2023",
    weights: [400, 700, 900],
    features: ["Case-Sensitive Forms", "Historical Forms", "All Caps"],
    inspiration: "8th century Chalukya temple inscriptions, UNESCO World Heritage Site",
    usage: ["Titles", "Monograms", "Brand Identity", "Cultural Institutions"],
  },
  {
    id: 15,
    name: "Udupi Round",
    nameKannada: "ಉಡುಪಿ ರೌಂಡ್",
    char: "ಉ",
    desc: "Soft, circular forms inspired by the temple town's coastal warmth and hospitality.",
    longDesc: "As warm and approachable as a plate of Udupi cuisine, Udupi Round is a rounded sans-serif designed to convey friendliness and approachability. Its soft terminals and generous spacing make it ideal for hospitality, food, and wellness brands.",
    styles: 6,
    category: "Sans",
    status: "Coming Soon",
    year: "2025",
    tag: "COMING SOON",
    weights: [300, 400, 500, 600, 700],
    features: ["Standard Ligatures", "Rounded Terminals"],
    inspiration: "Udupi's coastal hospitality temple town culture",
    usage: ["Food & Beverage", "Hospitality", "Wellness", "Children's Media"],
  },
  {
    id: 16,
    name: "Dharwad Gothic",
    nameKannada: "ಧಾರವಾಡ ಗಾಥಿಕ್",
    char: "ಧ",
    desc: "A compressed gothic for north Karnataka's industrial heritage.",
    longDesc: "Dharwad — the twin city of the north — has a distinct industrial character. Dharwad Gothic is a condensed, angular display typeface that channels the straightforward, no-nonsense character of this manufacturing belt into contemporary graphic applications.",
    styles: 4,
    category: "Display",
    status: "Coming Soon",
    year: "2025",
    weights: [400, 600, 700, 900],
    features: ["Case-Sensitive Forms", "Compressed Variants"],
    inspiration: "North Karnataka industrial architecture and signage",
    usage: ["Industrial Branding", "Merchandise", "Editorial"],
  },
];

// Featured fonts for homepage (subset)
export const featuredFonts = fontData.filter(f =>
  [5, 6, 11, 4, 3].includes(f.id)
);

// Get font by ID
export const getFontById = (id: number) =>
  fontData.find(f => f.id === id);
