export type FontCategory = "Serif" | "Sans" | "Display" | "Calligraphy" | "Heritage" | "Variable";
export type FontStatus = "Available" | "Coming Soon" | "Custom Only";

export interface FontVariant {
  label: string;
  cssFamily: string;
  weight: number;
}

export interface Font {
  id: number;
  slug: string;
  name: string;
  nameKannada: string;
  char: string;
  desc: string;
  longDesc: string;
  styles: number | "Variable";
  category: FontCategory;
  status: FontStatus;
  year: string;
  tag?: string;
  weights: number[];
  features: string[];
  inspiration: string;
  usage: string[];
  isReal?: boolean;
  primaryFamily?: string;
  variants?: FontVariant[];
  showcaseImages?: string[];
  downloadUrl?: string;
  previewText?: string;
  version?: string;
  designer?: string;
}

export const fontData: Font[] = [
  {
    id: 1,
    slug: "bandipura",
    name: "Bandipura",
    nameKannada: "ಬಂಡೀಪುರ",
    char: "ಶ",
    desc: "ATS Bandipura is an informal display typeface in Kannada and Latin script inspired by Elephant.",
    longDesc: "ATS Bandipura is an informal display typeface in Kannada and Latin script inspired by Elephant. Its thick, organic letterforms echo the weight and presence of the gentle giant, crafted for bold headlines, posters, and cultural branding that demand immediate attention.",
    styles: 1,
    category: "Display",
    status: "Available",
    year: "2022",
    tag: "FREE",
    weights: [700],
    features: ["OpenType", "Unicode 5.0", "Kannada Script", "Latin Script"],
    inspiration: "Elephant anatomy and the wildlife of Bandipur National Park, Karnataka",
    usage: ["Headlines", "Posters", "Heritage Branding", "Cultural Events", "Signage"],
    isReal: true,
    primaryFamily: "ATSBandipura",
    variants: [
      { label: "Bold", cssFamily: "ATSBandipura", weight: 700 },
    ],
    showcaseImages: [
      "/fonts/bandipura/showcase/ats-bandipura-01.webp",
      "/fonts/bandipura/showcase/ats-bandipura-02.webp",
      "/fonts/bandipura/showcase/ats-bandipura-03.webp",
      "/fonts/bandipura/showcase/ats-bandipura-04.webp",
      "/fonts/bandipura/showcase/ats-bandipura-05.webp",
      "/fonts/bandipura/showcase/ats-bandipura-06.webp",
      "/fonts/bandipura/showcase/ats-bandipura-07.webp",
      "/fonts/bandipura/showcase/ats-bandipura-08.webp",
      "/fonts/bandipura/showcase/ats-bandipura-09.webp",
    ],
    downloadUrl: "/fonts/bandipura/ATS-Bandipura.zip",
    previewText: "ಮಣ್ಣಿನ ಮಡಿಕೆಯ ಘಮಲು",
    version: "1.01",
    designer: "Manjunatha R",
  },
  {
    id: 2,
    slug: "bengaluru",
    name: "Bengaluru",
    nameKannada: "ಬೆಂಗಳೂರು",
    char: "ಬೆ",
    desc: "ATS Bengaluru is a Bitmap style font with a futuristic style, built on a clear geometric grid. Comes in 5 fonts and 2 styles, supporting Kannada and Latin.",
    longDesc: "ATS Bengaluru is a Bitmap style font with a futuristic style. This font looks modern and simple and built on a clear geometric grid. The font will give any work a unique look and is perfectly suitable to use on LED boards, print, games, web-sites, e-books, mobile applications. ATS Bengaluru comes in 5 Fonts (Dot, Pixel, Smooth, Square, LED), 2 Styles (Regular & Bold) and supports Kannada and Latin languages.",
    styles: 10,
    category: "Display",
    status: "Available",
    year: "2022",
    tag: "POPULAR",
    weights: [400, 700],
    features: ["OpenType", "Unicode 5.0", "Kannada Script", "Latin Script", "5 Sub-Families", "Bitmap Style"],
    inspiration: "Bengaluru LED hoardings, bus digital sign boards, MG Road pixel displays",
    usage: ["LED Boards", "Digital Signage", "Branding", "Posters", "Games", "Web", "Mobile"],
    isReal: true,
    primaryFamily: "ATSBengaluru-Smooth",
    variants: [
      { label: "Dot Regular",    cssFamily: "ATSBengaluru-Dot",    weight: 400 },
      { label: "Dot Bold",       cssFamily: "ATSBengaluru-Dot",    weight: 700 },
      { label: "LED Regular",    cssFamily: "ATSBengaluru-LED",    weight: 400 },
      { label: "LED Bold",       cssFamily: "ATSBengaluru-LED",    weight: 700 },
      { label: "Pixel Regular",  cssFamily: "ATSBengaluru-Pixel",  weight: 400 },
      { label: "Pixel Bold",     cssFamily: "ATSBengaluru-Pixel",  weight: 700 },
      { label: "Smooth Regular", cssFamily: "ATSBengaluru-Smooth", weight: 400 },
      { label: "Smooth Bold",    cssFamily: "ATSBengaluru-Smooth", weight: 700 },
      { label: "Square Regular", cssFamily: "ATSBengaluru-Square", weight: 400 },
      { label: "Square Bold",    cssFamily: "ATSBengaluru-Square", weight: 700 },
    ],
    showcaseImages: [
      "/fonts/bengaluru/showcase/ats-bengaluru-01.webp",
      "/fonts/bengaluru/showcase/ats-bengaluru-02.webp",
      "/fonts/bengaluru/showcase/ats-bengaluru-03.webp",
      "/fonts/bengaluru/showcase/ats-bengaluru-04.webp",
      "/fonts/bengaluru/showcase/ats-bengaluru-led-01.webp",
      "/fonts/bengaluru/showcase/ats-bengaluru-led-02.webp",
      "/fonts/bengaluru/showcase/ats-bengaluru-led-03.webp",
      "/fonts/bengaluru/showcase/ats-bengaluru-led-04.webp",
      "/fonts/bengaluru/showcase/ats-bengaluru-led-05.webp",
      "/fonts/bengaluru/showcase/ats-bengaluru-led-06.webp",
      "/fonts/bengaluru/showcase/ats-bengaluru-led-07.webp",
      "/fonts/bengaluru/showcase/ats-bengaluru-led-08.webp",
    ],
    downloadUrl: "/fonts/bengaluru/ATS-Bengaluru.zip",
    previewText: "ಬೆಂಗಳೂರು",
    designer: "Manjunatha R",
  },
  {
    id: 3,
    slug: "chikkamagaluru",
    name: "Chikkamagaluru",
    nameKannada: "ಚಿಕ್ಕಮಗಳೂರು",
    char: "ಚಿ",
    desc: "ATS Chikkamagaluru is a handwritten typeface inspired from kids writing in their books. The first Kannada color font, available in Regular and Color.",
    longDesc: "ATS Chikkamagaluru is a handwritten typeface inspired from kids writing character in their book. It is the first Kannada color font, capturing the charm and spontaneity of a child's handwriting. Available in 2 styles — Regular and Color — it brings warmth and playfulness to Kannada typography, perfect for children's media, educational materials, and joyful design.",
    styles: 2,
    category: "Display",
    status: "Available",
    year: "2024",
    tag: "NEW",
    weights: [400],
    features: ["OpenType", "Unicode 5.0", "Kannada Script", "Color Font (COLRv1)", "Handwritten Style"],
    inspiration: "Kids handwriting style and children's notebook characters",
    usage: ["Children's Media", "Educational", "Cultural Events", "Packaging", "Branding"],
    isReal: true,
    primaryFamily: "ATSChikkamagaluru",
    variants: [
      { label: "Regular",       cssFamily: "ATSChikkamagaluru",       weight: 400 },
      { label: "Color Regular", cssFamily: "ATSChikkamagaluru-Color", weight: 400 },
    ],
    showcaseImages: [
      "/fonts/chikkamagaluru/showcase/ats-chikkamagaluru-01.webp",
      "/fonts/chikkamagaluru/showcase/ats-chikkamagaluru-02.webp",
      "/fonts/chikkamagaluru/showcase/ats-chikkamagaluru-03.webp",
      "/fonts/chikkamagaluru/showcase/ats-chikkamagaluru-04.webp",
      "/fonts/chikkamagaluru/showcase/ats-chikkamagaluru-05.webp",
      "/fonts/chikkamagaluru/showcase/ats-chikkamagaluru-06.webp",
    ],
    downloadUrl: "/fonts/chikkamagaluru/ATS-Chikkamagaluru.zip",
    previewText: "ಚಿಕ್ಕಮಗಳೂರು",
    designer: "Manjunatha R",
  },
  {
    id: 4,
    slug: "kadamba-display",
    name: "Kadamba Display",
    nameKannada: "ಕಾದಂಬ ಡಿಸ್ಪ್ಲೇ",
    char: "ಕಾ",
    desc: "High-contrast display face inspired by 4th-century royal inscriptions.",
    longDesc: "The Kadamba dynasty gave Karnataka its first script. This typeface reconstructs the angular authority of Kadamba-era stone tablets into a razor-sharp display face for titles, posters, and brand marks requiring regal weight.",
    styles: 6,
    category: "Heritage",
    status: "Coming Soon",
    year: "2025",
    tag: "COMING SOON",
    weights: [400, 500, 600, 700, 800, 900],
    features: ["Contextual Alternates", "Case-Sensitive Forms", "Historical Forms"],
    inspiration: "4th century Kadamba dynasty stone inscriptions, Banavasi",
    usage: ["Headline", "Poster", "Brand Identity"],
  },
  {
    id: 5,
    slug: "sahitya-serif",
    name: "Sahitya Serif",
    nameKannada: "ಸಾಹಿತ್ಯ ಸೆರಿಫ್",
    char: "ಸ",
    desc: "Crafted for high-end editorial and complex literary layouts. Timeless and regal.",
    longDesc: "Named for Karnataka's rich literary tradition — Sahitya Serif is a workhorse for long-form Kannada publishing. Its generous x-height and carefully spaced ascenders make multi-column newspaper layouts effortless.",
    styles: 14,
    category: "Serif",
    status: "Coming Soon",
    year: "2025",
    weights: [100, 200, 300, 400, 500, 600, 700, 800, 900],
    features: ["Standard Ligatures", "Small Caps", "Oldstyle Figures", "Optical Size"],
    inspiration: "Classical Devanagari serifs adapted for Kannada letterforms",
    usage: ["Books", "Newspapers", "Magazines", "Academic"],
  },
  {
    id: 6,
    slug: "mysuru-mono",
    name: "Mysuru Mono",
    nameKannada: "ಮೈಸೂರು ಮೊನೊ",
    char: "ಮ",
    desc: "The studio's first monospaced typeface, bringing technical precision to Kannada code.",
    longDesc: "The palace city meets the terminal window. Mysuru Mono is a fixed-pitch typeface designed for developers who write Kannada. Every character occupies exactly the same width, enabling pixel-perfect alignment in code editors.",
    styles: 3,
    category: "Sans",
    status: "Coming Soon",
    year: "2025",
    weights: [400, 700],
    features: ["Tabular Figures", "Slashed Zero", "Coding Ligatures"],
    inspiration: "JetBrains Mono and Iosevka design principles adapted for Kannada",
    usage: ["Code Editors", "Terminal", "Technical Documentation"],
  },
  {
    id: 7,
    slug: "hampi-stone",
    name: "Hampi Stone",
    nameKannada: "ಹಂಪಿ ಸ್ಟೋನ್",
    char: "ಹ",
    desc: "Tactile and heavy, mimicking the granite carvings of the Vijayanagara empire.",
    longDesc: "Walking through Hampi's ruins, you see letters chiselled with an authority that no digital type can easily replicate. Hampi Stone is our attempt — a slab-serif with brutalist weight and incised letterforms drawn from site photography.",
    styles: 1,
    category: "Heritage",
    status: "Coming Soon",
    year: "2025",
    weights: [900],
    features: ["Historical Forms", "Case-Sensitive Forms"],
    inspiration: "15th-century Vijayanagara granite inscriptions, Hampi UNESCO site",
    usage: ["Titles", "Heritage Projects", "Museum Installations"],
  },
  {
    id: 8,
    slug: "vidhana-sans",
    name: "Vidhana Sans",
    nameKannada: "ವಿಧಾನ ಸ್ಯಾನ್ಸ್",
    char: "ವಿ",
    desc: "Authoritative and grand, designed for administrative and governmental clarity.",
    longDesc: "The Karnataka Vidhana Soudha is a monument to authority. Vidhana Sans takes its proportional cues from architectural neoclassicism, delivering a humanist sans that reads powerfully in large-format state communications and government publications.",
    styles: 7,
    category: "Sans",
    status: "Coming Soon",
    year: "2025",
    weights: [300, 400, 500, 600, 700, 800, 900],
    features: ["Standard Ligatures", "Fractions", "Small Caps", "Tabular Figures"],
    inspiration: "Humanist sans proportions with Vidhana Soudha architectural geometry",
    usage: ["Government", "Institutional", "Wayfinding", "Signs"],
  },
  {
    id: 9,
    slug: "kavi-script",
    name: "Kavi Script",
    nameKannada: "ಕವಿ ಲಿಪಿ",
    char: "ಕ",
    desc: "A flowing cursive inspired by 18th-century royal correspondence.",
    longDesc: "Discovered in the Mysuru Palace library, a collection of Woddeyar dynastic letters penned in an exquisite cursive hand formed the blueprint for Kavi Script. Each letterform is traced directly from archival photographs, then refined for digital precision.",
    styles: 2,
    category: "Calligraphy",
    status: "Coming Soon",
    year: "2025",
    weights: [400, 700],
    features: ["Contextual Swashes", "Historical Forms", "Stylistic Sets"],
    inspiration: "18th-century Mysuru Woddeyar palace correspondence manuscripts",
    usage: ["Invitations", "Luxury Packaging", "Certificates", "Heritage Branding"],
  },
  {
    id: 10,
    slug: "tunga-variable",
    name: "Tunga Variable",
    nameKannada: "ತುಂಗ ವೇರಿಯೇಬಲ್",
    char: "ತು",
    desc: "Infinite weights in one file. The future of Kannada responsive typography.",
    longDesc: "Named for the Tunga river that mirrors the sky, Tunga Variable is a full-axis variable font with continuous control over Weight, Width, and Optical Size axes. One file replaces a complete family while enabling micro-typographic nuance impossible before variable technology.",
    styles: "Variable",
    category: "Variable",
    status: "Coming Soon",
    year: "2025",
    tag: "VARIABLE",
    weights: [100, 900],
    features: ["Variable Weight Axis", "Variable Width Axis", "Optical Size Axis", "All OpenType Features"],
    inspiration: "Variable font technology with Tunga river organic curves",
    usage: ["Responsive Web", "App UI", "All Contexts"],
  },
  {
    id: 11,
    slug: "karavali-display",
    name: "Karavali Display",
    nameKannada: "ಕರಾವಳಿ ಡಿಸ್ಪ್ಲೇ",
    char: "ಕ",
    desc: "Bold and fluid as the Arabian sea. Perfect for branding and posters.",
    longDesc: "Born from the Tulu coast, where the land and sea are in constant dialogue, Karavali Display captures the energy of coastal Karnataka. Its wave-like counters and dynamic stroke contrast make it ideal for bold brand expressions.",
    styles: 5,
    category: "Display",
    status: "Coming Soon",
    year: "2025",
    weights: [400, 500, 600, 700, 900],
    features: ["Contextual Alternates", "Stylistic Alternates", "Swashes"],
    inspiration: "Arabian sea waves meeting the Karnataka coastal rock formations",
    usage: ["Branding", "Posters", "Packaging", "Social Media"],
  },
  {
    id: 12,
    slug: "coorg-slab",
    name: "Coorg Slab",
    nameKannada: "ಕೊಡಗು ಸ್ಲ್ಯಾಬ್",
    char: "ಕ",
    desc: "A robust slab-serif built for outdoor advertising in the hill districts.",
    longDesc: "Designed for durability and impact in the misty hills of Kodagu, Coorg Slab is a heavy slab-serif that reads at distance and at scale. Its squared serifs and sturdy strokes resist visual noise in complex environments.",
    styles: 5,
    category: "Serif",
    status: "Coming Soon",
    year: "2025",
    weights: [300, 400, 600, 700, 800],
    features: ["Standard Ligatures", "Tabular Figures", "Small Caps"],
    inspiration: "Outdoor advertising in Kodagu's coffee estate hoardings",
    usage: ["Outdoor Advertising", "Packaging", "Retail"],
  },
  {
    id: 13,
    slug: "pattadakal-caps",
    name: "Pattadakal Caps",
    nameKannada: "ಪಟ್ಟದಕಲ್ ಕ್ಯಾಪ್ಸ್",
    char: "ಪ",
    desc: "All-caps heritage display inspired by UNESCO Chalukya temple inscriptions.",
    longDesc: "The Chalukya temples of Pattadakal bear some of the most sophisticated inscriptions in Indian heritage. Pattadakal Caps distils the architectural geometry of 8th-century Chalukya letterforms into a contemporary all-caps display face.",
    styles: 3,
    category: "Heritage",
    status: "Coming Soon",
    year: "2025",
    weights: [400, 700, 900],
    features: ["Case-Sensitive Forms", "Historical Forms", "All Caps"],
    inspiration: "8th century Chalukya temple inscriptions, UNESCO World Heritage Site",
    usage: ["Titles", "Monograms", "Brand Identity", "Cultural Institutions"],
  },
];

export const getFontBySlug = (slug: string): Font | undefined =>
  fontData.find(f => f.slug === slug);

export const getFontById = (id: number): Font | undefined =>
  fontData.find(f => f.id === id);

export const realFonts = fontData.filter(f => f.isReal);

export const featuredFonts = fontData.filter(f => [1, 2, 3].includes(f.id));
